DjangoMyblog/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    # 配置url
    # 可以把应用模块的总路径配置在这边，然后具体细分模块下的url
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^index/$', views.index),   # 可以带正则表达式
    url(r'^article/(?P<article_id>[0-9]+)/$', views.show_article, name='article_page'),
    url('edit/(?P<article_id>[0-9]+)/$', views.edit_article, name='edit_page'),
    url('edit_action/', views.edit_action, name='edit_action'),
]

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30, default="Hello")
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

# Create your views here.


# 响应  localhost:8000/blog/index
def index(request):
    # return HttpResponse("hello world")
    # all 返回的就是一个django封装的类似于list的结果集，直接可用于循环
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def show_article(request, article_id):
    article = models.Article.objects.get(id=article_id)
    return render(request, 'blog/articlePage.html', {'article': article})


def edit_article(request, article_id):
    if article_id == '0':
        return render(request, 'blog/editArticle.html')
    article = models.Article.objects.get(id=article_id)
    return render(request, 'blog/editArticle.html', {'article': article})


def edit_action(request):
    # 分情况，若是新建就是create，若是更改则是save对象
    title = request.POST['title']
    content = request.POST['content']
    article_id = request.POST['article_id']
    if article_id == '0':
        article = models.Article.objects.create(title=title, content=content)
        return render(request, 'blog/articlePage.html', {'article': article})
    else:
        article = models.Article.objects.get(id=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/articlePage.html', {'article': article})

blog/templates/blog/articlePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>articlePage</title>
</head>
<body>
<h1>
    {{ article.title }}
</h1>
<hr/>
<h2>
    {{ article.content }}
</h2>
<a href="{% url 'blog:edit_page' article.id %}">edit</a>
</body>
</html>

blog/templates/blog/editArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
{#    过滤器#}
     <input type="hidden" value="{{ article.id | default:'0'}}" name="article_id">
     Title:<input type="text" name="title" value="{{ article.title }}"/><br>
     Content:<input type="text" name="content" value="{{ article.content }}"/><br>
     <input type="submit">

{#    {% if article %}#}
{#        <input type="hidden" value="{{ article.id }}" name="article_id">#}
{#        Title:<input type="text" name="title" value="{{ article.title }}"/><br>#}
{#        Content:<input type="text" name="content" value="{{ article.content }}"/><br>#}
{#        <input type="submit">#}
{#    {% else %}#}
{#        <input type="hidden" value="0" name="article_id">#}
{#        Title:<input type="text" name="title"/><br>#}
{#        Content:<input type="text" name="content"/><br>#}
{#    <input type="submit">#}
{#    {% endif %}#}
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>
    <a href="{% url 'blog:edit_page' 0 %}">new</a>
</h2>

{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br>
{% endfor %}
</body>
</html>